-- MySQL Script generated by MySQL Workbench
-- Thu Oct 20 13:10:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id` INT NOT NULL,
  `telefono` VARCHAR(12) NULL,
  `correoElectronico` VARCHAR(50) NULL,
  `claveAcceso` VARCHAR(50) NULL,
  `tipo` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `id` INT NOT NULL,
  `noPersonal` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidoPaterno` VARCHAR(50) NOT NULL,
  `apellidoMaterno` VARCHAR(50) NULL,
  `estatus` TINYINT(1) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `noPersonal_UNIQUE` (`noPersonal` ASC) VISIBLE,
  INDEX `fk_Empleado_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Empleado_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PlanEstudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PlanEstudio` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `clave` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `clave_UNIQUE` (`clave` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grado` (
  `id` INT NOT NULL,
  `clave` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `idPlanEstudio` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `clave_UNIQUE` (`clave` ASC) VISIBLE,
  INDEX `fk_Grado_PlanEstudio1_idx` (`idPlanEstudio` ASC) VISIBLE,
  CONSTRAINT `fk_Grado_PlanEstudio1`
    FOREIGN KEY (`idPlanEstudio`)
    REFERENCES `mydb`.`PlanEstudio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Materia` (
  `id` INT NOT NULL,
  `clave` VARCHAR(30) NOT NULL,
  `horasPracticas` INT NOT NULL,
  `horasTeoricas` INT NOT NULL,
  `nombre` VARCHAR(40) NOT NULL,
  `estatus` TINYINT(1) NOT NULL,
  `idGrado` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `clave_UNIQUE` (`clave` ASC) VISIBLE,
  INDEX `fk_Materia_Grado1_idx` (`idGrado` ASC) VISIBLE,
  CONSTRAINT `fk_Materia_Grado1`
    FOREIGN KEY (`idGrado`)
    REFERENCES `mydb`.`Grado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evaluacion` (
  `id` INT NOT NULL,
  `calificacion` VARCHAR(15) NULL,
  `tipo` VARCHAR(50) NULL,
  `Materia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Evaluacion_Materia1_idx` (`Materia_id` ASC) VISIBLE,
  CONSTRAINT `fk_Evaluacion_Materia1`
    FOREIGN KEY (`Materia_id`)
    REFERENCES `mydb`.`Materia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumno` (
  `id` INT NOT NULL,
  `matricula` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidoPaterno` VARCHAR(50) NOT NULL,
  `apellidoMaterno` VARCHAR(50) NULL,
  `curp` VARCHAR(20) NOT NULL,
  `estatus` TINYINT(1) NOT NULL,
  `idUsuario` INT NOT NULL,
  `Evaluacion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) VISIBLE,
  UNIQUE INDEX `curp_UNIQUE` (`curp` ASC) VISIBLE,
  INDEX `fk_Alumno_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Alumno_Evaluacion1_idx` (`Evaluacion_id` ASC) VISIBLE,
  CONSTRAINT `fk_Alumno_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_Evaluacion1`
    FOREIGN KEY (`Evaluacion_id`)
    REFERENCES `mydb`.`Evaluacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Edificio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Edificio` (
  `id` INT NOT NULL,
  `clave` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `estatus` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `clave_UNIQUE` (`clave` ASC) VISIBLE,
  UNIQUE INDEX `estatus_UNIQUE` (`estatus` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Salon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Salon` (
  `id` INT NOT NULL,
  `clave` VARCHAR(20) NOT NULL,
  `capacidad` INT NOT NULL,
  `estatus` TINYINT(1) NOT NULL,
  `idEdificio` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `clave_UNIQUE` (`clave` ASC) VISIBLE,
  INDEX `fk_Salon_Edificio_idx` (`idEdificio` ASC) VISIBLE,
  CONSTRAINT `fk_Salon_Edificio`
    FOREIGN KEY (`idEdificio`)
    REFERENCES `mydb`.`Edificio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PeriodoEscolar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PeriodoEscolar` (
  `id` INT NOT NULL,
  `clave` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `clave_UNIQUE` (`clave` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grupo` (
  `id` INT NOT NULL,
  `clave` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `idGrado` INT NOT NULL,
  `idPeriodoEscolar` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `clave_UNIQUE` (`clave` ASC) VISIBLE,
  INDEX `fk_Grupo_Grado1_idx` (`idGrado` ASC) VISIBLE,
  INDEX `fk_Grupo_PeriodoEscolar1_idx` (`idPeriodoEscolar` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_Grado1`
    FOREIGN KEY (`idGrado`)
    REFERENCES `mydb`.`Grado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_PeriodoEscolar1`
    FOREIGN KEY (`idPeriodoEscolar`)
    REFERENCES `mydb`.`PeriodoEscolar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clase` (
  `id` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  `idMateria` INT NOT NULL,
  `idGrupo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Clase_Empleado1_idx` (`idEmpleado` ASC) VISIBLE,
  INDEX `fk_Clase_Materia1_idx` (`idMateria` ASC) VISIBLE,
  INDEX `fk_Clase_Grupo1_idx` (`idGrupo` ASC) VISIBLE,
  CONSTRAINT `fk_Clase_Empleado1`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clase_Materia1`
    FOREIGN KEY (`idMateria`)
    REFERENCES `mydb`.`Materia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clase_Grupo1`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `mydb`.`Grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Horario` (
  `id` INT NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  `idSalon` INT NOT NULL,
  `idClase` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Horario_Salon1_idx` (`idSalon` ASC) VISIBLE,
  INDEX `fk_Horario_Clase1_idx` (`idClase` ASC) VISIBLE,
  CONSTRAINT `fk_Horario_Salon1`
    FOREIGN KEY (`idSalon`)
    REFERENCES `mydb`.`Salon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horario_Clase1`
    FOREIGN KEY (`idClase`)
    REFERENCES `mydb`.`Clase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inscripcion` (
  `id` INT NOT NULL,
  `fechaRegistro` DATE NOT NULL,
  `idGrupo` INT NOT NULL,
  `idPeriodoEscolar` INT NOT NULL,
  `idAlumno` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Inscripcion_Grupo1_idx` (`idGrupo` ASC) VISIBLE,
  INDEX `fk_Inscripcion_PeriodoEscolar1_idx` (`idPeriodoEscolar` ASC) VISIBLE,
  INDEX `fk_Inscripcion_Alumno1_idx` (`idAlumno` ASC) VISIBLE,
  CONSTRAINT `fk_Inscripcion_Grupo1`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `mydb`.`Grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripcion_PeriodoEscolar1`
    FOREIGN KEY (`idPeriodoEscolar`)
    REFERENCES `mydb`.`PeriodoEscolar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripcion_Alumno1`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `mydb`.`Alumno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
